Script started on 2015年03月11日 (週三) 21時21分46秒
]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ script lab1.script[5Pgit config -l-global user.email  "f74034059@mail.ncku.edu.tw"e"[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cname "[18PF74034059"[A]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ [C[C[C[C[Clone https://githun.com/F74034059/lab1.git[A]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[1Pwhoami; pwdscript lab1.scriptgit push -u origin mastercommit[Kstatusadd F74034059.cpp[10P./F74034059g++ -o F74034059 F74034059.cpp [A
g++: error: F74034059.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ cd lab1
]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ cd lab1g++ -o F74034059 F740340599.cpp
]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ g++ -o F74034059 F740340599.cpp[A]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ cd lab1[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cg++ -o F74034059 F740340599.cpp[A]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ [7Pscript lab1.script
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[5Pgit config -l-global user.eemail "f74034059@mail.ncku.edu.tw"e"[18Pname "F74034059"[A]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ [C[C[C[C[Clone https://githun.com/F74034059/lab1.git[A]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ [C[C[C[C[C[12Ponfig -l
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[1Pwhoami; pwdscript lab1.scriptgit push -u origin master [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Ccommit[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cstatusadd F74034059.cpp[10P./F74034059g++ -o F74034059 F740340599.cpp[A]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ [14P./F74034059
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;F74034059@2015cpp: ~/lab1F74034059@2015cpp:~/lab1$ exit

Script done on 2015年03月11日 (週三) 21時22分43秒
