Script started on 2015年03月11日 (週三) 19時51分10秒
]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ whoami; pwd
F74034059
/home/F74034059
]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ git confgi[K[Kig -l
user.name=F74034059
user.email=f74034059@mail.ncku.edu.tw
]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ git clone https://github.co m/F74034059/;[Klab1.git [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
[C[C[C[C[C[C[C[C[C[C[C[C
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74034059@2015cpp: ~F74034059@2015cpp:~$ exit

Script done on 2015年03月11日 (週三) 19時52分29秒
